[package]
name = "tunio-utun"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
delegate.workspace = true
derive_builder.workspace = true
futures.workspace = true
libc.workspace = true
log.workspace = true
netconfig.workspace = true
nix.workspace = true
socket2 = "0.5.7"
tunio-core.workspace = true

[features]
tokio = ["tunio-core/tokio"]
