[package]
name = "tunio-wintun"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-task = "4.3.0"
blocking = "1.3.0"
bytes = "1.2.0"
delegate.workspace = true
derive_builder.workspace = true
futures.workspace = true
log.workspace = true
netconfig.workspace = true
tunio-core.workspace = true
widestring = "1.0.2"
windows-sys = { version = "0.59", features = [
    "Win32_System_Threading",
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_WindowsProgramming",
    "Win32_NetworkManagement_IpHelper",
    "Win32_NetworkManagement_Ndis",
    "Win32_System_Com",
] }
wintun-sys = { version = "0.2.0", path = "../../wintun-sys" }
